# Блок заданий 01: работа с массивами

## Вспомогательный код

*(Можно не смотреть, но надо запустить)*

In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [2]:
ok = set()  # это служебная структура, чтобы Вам было проще смотреть все ли задания выполнены
all_tasks = (
    {f'1.{i}' for i in range(1, 8)} |
    {f'2.{i}' for i in range(1, 9)} |
    {f'3.{i}' for i in range(1, 4)}
)

## Задания

### 1. Операции индексирования

Дана матрица $A \in \mathbb{R}^{5 \times 3}$:

In [3]:
A = np.arange(1, 16).reshape((5, 3)).copy()
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

Никогда не изменяйте эту матрицу.

**Задание:** с помощью операций индексирования получите следующие матрицы (по возможности использующие ту же память):

#### 1.1. `[[1, 2, 3], [7, 8, 9], [13, 14, 15]]`

In [66]:
A_1_1 = A[::2]

In [67]:
A_1_1

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [68]:
assert A_1_1.base is A, 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_1_1, np.array([
    [ 1,  2,  3],
    [ 7,  8,  9],
    [13, 14, 15]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('1.1')

#### 1.2. `[[13, 14, 15], [10, 11, 12] [7, 8, 9], [4, 5, 6], [1, 2, 3]]`

In [7]:
A_1_2 = A[::-1]

In [8]:
A_1_2

array([[13, 14, 15],
       [10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [9]:
assert A_1_2.base is A, 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_1_2, np.array([
    [13, 14, 15],
    [10, 11, 12],
    [ 7,  8,  9],
    [ 4,  5,  6],
    [ 1,  2,  3]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('1.2')

#### 1.3. `[[13, 14, 15], [7, 8, 9], [1, 2, 3]]`

In [10]:
A_1_3 = A[::-2]

In [11]:
A_1_3

array([[13, 14, 15],
       [ 7,  8,  9],
       [ 1,  2,  3]])

In [12]:
assert A_1_3.base is A, 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_1_3, np.array([
    [13, 14, 15],
    [ 7,  8,  9],
    [ 1,  2,  3]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('1.3')

#### 1.4. `[[15, 14, 13], [9, 8, 7], [3, 2, 1]]`

In [13]:
A_1_4 = A[::-2, ::-1]

In [14]:
A_1_4

array([[15, 14, 13],
       [ 9,  8,  7],
       [ 3,  2,  1]])

In [15]:
assert A_1_4.base is A, 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_1_4, np.array([
    [15, 14, 13],
    [ 9,  8,  7],
    [ 3,  2,  1]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('1.4')

#### 1.5. `[[5, 6], [8, 9]]`

In [16]:
A_1_5 = A[1:3, 1:3]

In [17]:
A_1_5

array([[5, 6],
       [8, 9]])

In [18]:
assert A_1_5.base is A, 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_1_5, np.array([
    [5, 6],
    [ 8,  9],
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('1.5')

#### 1.6. `[[1, 2, 3], [4, 5, 6], [13, 14, 15]]`.

*(Используйте индексирование списком)*

In [19]:
A_1_6 = A[[0, 1, 4]]

In [20]:
A_1_6

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [13, 14, 15]])

In [21]:
assert np.allclose(A_1_6, np.array([
    [ 1,  2,  3],
    [ 4,  5,  6],
    [13, 14, 15]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('1.6')

#### 1.7. ⭐️ Доп. задание `[[3, 2, 1], [4, 5, 6], [15, 14, 13]]`.

*Это дополнительное задание. Его нельзя выполнять составляя матрицу поэлементно (типа `np.array([[3, 2, 1], ...])`), но можно использовать другие операции NumPy, например конкатенацию.*

In [75]:
A_1_7 = np.concatenate([A[0:1, ::1], A[1:2], A[4:5, ::1]])

In [76]:
A_1_7

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [13, 14, 15]])

In [77]:
assert np.allclose(A_1_7, np.array([
    [ 3,  2,  1],
    [ 4,  5,  6],
    [15, 14, 13]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('1.7')

AssertionError: Ошибка, переделайте или пропускайте задание

### 2. Работа с многомерными массивами

**Задание:** с помощью встроенных операций создайте массив и заполните его значениями.

**Запрещается** создавать матрицу с помощью `np.array([...])`, а также заполнять поэлементно, например:
`A_2_1[0, 0] = 0; ...`.

#### 2.1. Матрица из нулей размерности 3 на 4

In [22]:
A_2_1 = np.zeros((3, 4))

In [23]:
A_2_1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
assert A_2_1.shape == (3, 4), 'Ошибка, переделайте или пропускайте задание'
assert np.sum(np.abs(A_2_1)) == 0., 'Ошибка, переделайте или пропускайте задание'
ok.add('2.1')

#### 2.2. Матрица размерности 3 на 4, заполненная числом 5

In [25]:
A_2_2 = np.full((3, 4), 5)

In [26]:
A_2_2

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [27]:
assert A_2_2.shape == (3, 4), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_2_2, 5), 'Ошибка, переделайте или пропускайте задание'
ok.add('2.2')

#### 2.3. Матрица размерности 3 на 4, заполненная числами от 0 до 11 слева направо сверху вниз

Должно получиться:
```
[ 0,  1,  2,  3]
[ 4,  5,  6,  7]
[ 8,  9, 10, 11]
```

In [40]:
A_2_3 = np.arange(12).reshape(3, 4)

In [41]:
A_2_3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
assert A_2_3.shape == (3, 4), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_2_3, np.array([
    [ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('2.3')

#### 2.4. Матрица размерности 4 на 3, заполненная числами от 0 до 11 сверху вниз слева направо

Должно получиться:
```
[ 0,  4,  8]
[ 1,  5,  9]
[ 2,  6, 10]
[ 3,  7, 11]
```

In [45]:
A_2_4 = np.arange(12).reshape(3, 4).transpose()

In [46]:
A_2_4

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [47]:
assert A_2_4.shape == (4, 3), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_2_4, np.array([
    [ 0,  4,  8],
    [ 1,  5,  9],
    [ 2,  6, 10],
    [ 3,  7, 11]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('2.4')

#### 2.5. Трёхмерный массив размерности 2 на 3 на 4, заполненный числами от 0 до 23 в естественном порядке

Должно получиться:
```
[[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11]],

[[12, 13, 14, 15],
 [16, 17, 18, 19],
 [20, 21, 22, 23]]
```

In [48]:
A_2_5 = np.arange(24).reshape(2, 3, 4)

In [49]:
A_2_5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [50]:
assert A_2_5.shape == (2, 3, 4), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_2_5, np.array([
    [[ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11]],

   [[12, 13, 14, 15],
    [16, 17, 18, 19],
    [20, 21, 22, 23]]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('2.5')

#### 2.6. Из предыдущего массива `A_2_5` извлеките подмассив со следующим содержимым:

```
[[ 1,  2],
 [ 5,  6],
 [ 9, 10]],

[[13, 14],
 [17, 18],
 [21, 22]]
```

**Нельзя создавать новый массив, надо обязательно использовать `A_2_5`**

In [51]:
A_2_6 = A_2_5[:, :, 1:3]

In [52]:
A_2_6

array([[[ 1,  2],
        [ 5,  6],
        [ 9, 10]],

       [[13, 14],
        [17, 18],
        [21, 22]]])

In [53]:
assert A_2_6.shape == (2, 3, 2), 'Ошибка, переделайте или пропускайте задание'
assert (A_2_6.base is A_2_5.base) or (A_2_6.base is A_2_5), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_2_6, np.array([
    [[ 1,  2],
    [ 5,  6],
    [ 9, 10]],

    [[13, 14],
    [17, 18],
    [21, 22]]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('2.6')

#### 2.7. Преобразуйте массив `A_2_5`, чтобы получить следующее содержимое:

```
[[[ 0, 12],
[ 4, 16],
[ 8, 20]],

[[ 1, 13],
[ 5, 17],
[ 9, 21]],

[[ 2, 14],
[ 6, 18],
[10, 22]],

[[ 3, 15],
[ 7, 19],
[11, 23]]]
```

И размерности `(4, 3, 2)`.

**Нельзя создавать новый массив, надо обязательно использовать `A_2_5`**

In [57]:
A_2_7 = np.transpose(A_2_5, (2, 1, 0))

In [58]:
A_2_7.shape

(4, 3, 2)

In [59]:
A_2_7

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [60]:
assert A_2_7.shape == (4, 3, 2), 'Ошибка, переделайте или пропускайте задание'
assert (A_2_7.base is A_2_5.base) or (A_2_7.base is A_2_5), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_2_7, np.array([
    [[ 0, 12],
    [ 4, 16],
    [ 8, 20]],
    
    [[ 1, 13],
    [ 5, 17],
    [ 9, 21]],
    
    [[ 2, 14],
    [ 6, 18],
    [10, 22]],
    
    [[ 3, 15],
    [ 7, 19],
    [11, 23]]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('2.7')

#### 2.8. Преобразуйте массив `A_2_5`, чтобы получить размерность `(6, 4)` и следующее содержимое:

```
[[ 0,  1,  2,  3],
[ 4,  5,  6,  7],
[ 8,  9, 10, 11],
[12, 13, 14, 15],
[16, 17, 18, 19],
[20, 21, 22, 23]]
```

**Нельзя создавать новый массив, надо обязательно использовать `A_2_5`**

In [61]:
A_2_8 = A_2_5.reshape(6, 4)

In [62]:
A_2_8.shape

(6, 4)

In [63]:
A_2_8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
assert A_2_8.shape == (6, 4), 'Ошибка, переделайте или пропускайте задание'
assert (A_2_8.base is A_2_5.base) or (A_2_8.base is A_2_5), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_2_8, np.array([
    [ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11],
    [12, 13, 14, 15],
    [16, 17, 18, 19],
    [20, 21, 22, 23]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('2.8')

### 3. Изменение массивов

**Задание:** в каждой задаче (3.1., 3.2., ...) дан массив, его требуется изменить определённым образом.
Как и в прошлом задании, запрещается изменять массив поэлементно (например: `A_3_1[0, 0, 0] = 0; ...`).

**Не изменяйте массив `A_3_orig`**.


#### Подготовка

In [65]:
# здесь матрица создаётся вручную, чтобы не упрощать выполнение предыдущих заданий,
# на практике никогда не применяйте такой подход для крупных матриц
A_3_orig = np.array([
    [[ 0,  1,  2,  3],
     [ 4,  5,  6,  7],
     [ 8,  9, 10, 11]],
    
    [[12, 13, 14, 15],
     [16, 17, 18, 19],
     [20, 21, 22, 23]]
])

#### 3.1. Заполните числом 25 все элементы, хотя бы один из индексов (i, j, k) которых является чётным

Нумерация идёт с нуля, т.е., например, элементы `A_3_2[0, 0, 0], A_3_2[0, 0, 2], A_3_2[0, 2, 0]` подпадают под критерий, и должны быть заменены на $25$.

Должно получиться:
```
[[25, 25, 25, 25],
[25, 25, 25, 25],
[25, 25, 25, 25]],

[[25, 25, 25, 25],
[25, 17, 25, 19],
[25, 25, 25, 25]]]
```

In [132]:
A_3_1 = A_3_orig.copy()

In [133]:
A_3_1[::2] = 25
A_3_1[:,::2] = 25
A_3_1[:,:,::2] = 25

In [134]:
A_3_1

array([[[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]],

       [[25, 25, 25, 25],
        [25, 17, 25, 19],
        [25, 25, 25, 25]]])

In [135]:
assert A_3_1.shape == (2, 3, 4), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_3_1, [
    [[25, 25, 25, 25],
    [25, 25, 25, 25],
    [25, 25, 25, 25]],
    
    [[25, 25, 25, 25],
    [25, 17, 25, 19],
    [25, 25, 25, 25]]
]), 'Ошибка, переделайте или пропускайте задание'
ok.add('3.1')

#### 3.2. Заполните числом 25 все элементы, где все индексы (i, j, k) являются чётными одновременно

Нумерация идёт с нуля, т.е., например, элементы `A_3_2[0, 0, 0], A_3_2[2, 2, 2]` подпадают под критерий, и должны быть заменены на $25$.

Должно получиться:
```
[[[25,  1, 25,  3],
[ 4,  5,  6,  7],
[25,  9, 25, 11]],

[[12, 13, 14, 15],
[16, 17, 18, 19],
[20, 21, 22, 23]]]
```

In [137]:
A_3_2 = A_3_orig.copy()

In [138]:
A_3_2[::2,::2,::2] = 25

In [139]:
A_3_2

array([[[25,  1, 25,  3],
        [ 4,  5,  6,  7],
        [25,  9, 25, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [140]:
assert A_3_2.shape == (2, 3, 4), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_3_2, [
    [[[25,  1, 25,  3],
    [ 4,  5,  6,  7],
    [25,  9, 25, 11]],
    
    [[12, 13, 14, 15],
    [16, 17, 18, 19],
    [20, 21, 22, 23]]]
]), 'Ошибка, переделайте или пропускайте задание'
ok.add('3.2')

#### 3.3. Заполните числом 25 все элементы по индексам (0, 1, 2), (1, 2, 3), (0, 2, 1), (1, 0, 0)

Должно получиться:
```
[[[ 0,  1,  2,  3],
[ 4,  5, 25,  7],
[ 8, 25, 10, 11]],

[[25, 13, 14, 15],
[16, 17, 18, 19],
[20, 21, 22, 25]]]
```

Предполагается, что использовать поэлементный доступ нельзя, то есть `A_3_3[0, 1, 2] = 25; A_3_3[1, 2, 3] = 25; ...` – **не решение**.

Решение должно занимать одну строку (без `;`).

*Посмотрите сперва почему именно такой результат должен получиться.*

In [116]:
A_3_3 = A_3_orig.copy()

In [118]:
indices = [(0, 1, 2), (1, 2, 3), (0, 2, 1), (1, 0, 0)]

In [141]:
A_3_3[[0, 1, 0, 1], [1, 2, 2, 0], [2, 3, 1, 0]] = 25

In [142]:
A_3_3

array([[[ 0,  1,  2,  3],
        [ 4,  5, 25,  7],
        [ 8, 25, 10, 11]],

       [[25, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 25]]])

In [143]:
assert A_3_3.shape == (2, 3, 4), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_3_3, [
    [[ 0,  1,  2,  3],
    [ 4,  5, 25,  7],
    [ 8, 25, 10, 11]],
    
    [[25, 13, 14, 15],
    [16, 17, 18, 19],
    [20, 21, 22, 25]]
]), 'Ошибка, переделайте или пропускайте задание'
ok.add('3.3')

## Итоги

In [144]:
print(f'Выполнены задания: {ok}')
print(f'Осталось: {all_tasks - ok}')

Выполнены задания: {'2.4', '2.6', '1.5', '2.5', '3.3', '1.2', '1.6', '2.3', '1.1', '1.4', '2.2', '2.7', '3.1', '3.2', '1.3', '2.8', '2.1', '1.7'}
Осталось: set()
