# Блок заданий 02: обработка массивов

## Вспомогательный код

*(Можно не смотреть, но надо запустить)*

In [72]:
import numpy as np
from matplotlib import pyplot as plt

In [73]:
ok = set()  # это служебная структура, чтобы Вам было проще смотреть все ли задания выполнены
all_tasks = (
    {f'1.{i}' for i in range(1, 3)} |
    {f'2.{i}' for i in range(1, 5)} |
    {f'3.{i}' for i in range(1, 3)}
)

## Задания

### 1. Статистические функции

Дана матрица $A \in \mathbb{R}^{5 \times 3}$:

In [74]:
A = np.arange(1, 16).reshape((5, 3)).copy()
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

Никогда не изменяйте эту матрицу.

**Задание:** с помощью стандартных операций найдите

#### 1.1. Среднее для каждой строки

Т.е. должен получиться вектор, элементами которого являются средние значения по каждой из строк $A$

In [75]:
answer_1_1 = A.mean(axis=1)

In [76]:
answer_1_1

array([ 2.,  5.,  8., 11., 14.])

In [77]:
assert answer_1_1.shape == (5,), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(answer_1_1, np.array([2.,  5.,  8., 11., 14.])), 'Ошибка, переделайте или пропускайте задание'
ok.add('1.1')

#### 1.2. Стандартизуйте матрицу $A$

Каждая строка рассматривается как отдельное наблюдение случайного вектора. То есть всего 5 наблюдений вектора, каждый размерности 3.

Для каждого слолбца должно быть верно, что среднее равно $0$, а стандартное отклонение равно $1$:

$$
\hat{x}_i = \frac{x_i - \mu_i}{\sigma_i},
$$
где $x_i$ – $i$-я компонента вектора, $\mu_i$ – среднее значение, $\sigma_i$ – стандартное отклонение.

**В ответе должна быть новая матрица, не изменяйте саму $A$.**

In [78]:
answer_1_2 = (A - A.mean(axis=0)) / A.std(axis=0)

In [79]:
answer_1_2

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])

In [80]:
assert np.allclose(np.mean(answer_1_2, 0), 0), 'Ошибка (среднее по строкам должно быть нулём), переделайте или пропускайте задание'
assert np.allclose(np.std(answer_1_2, 0), 1.), 'Ошибка (стандартное отклонение должно быть 1), переделайте или пропускайте задание'
assert np.allclose(answer_1_2, np.array([
    [-1.41421356, -1.41421356, -1.41421356],
    [-0.70710678, -0.70710678, -0.70710678],
    [ 0.        ,  0.        ,  0.        ],
    [ 0.70710678,  0.70710678,  0.70710678],
    [ 1.41421356,  1.41421356,  1.41421356]
])), 'Ошибка (должна быть стандартизована матрица A), переделайте или пропускайте задание'
ok.add('1.2')

### 2. Фильтрация элементов

**Задание:** отфильтруйте элементы заданной матрицы по описанным критериям.

**Запрещается** создавать матрицу с помощью `np.array([...])`, а также заполнять поэлементно, например:
`A_2_1[0, 0] = 0; ...`. Подразумевается использование булевого индексирования.

#### Подготовка

In [81]:
# здесь матрица создаётся вручную, чтобы не упрощать выполнение предыдущих заданий,
# на практике никогда не применяйте такой подход для крупных матриц
A_2_orig = np.array([
    [[ 0,  1,  2,  3],
     [ 4,  5,  6,  7],
     [ 8,  9, 10, 11]],
    
    [[12, 13, 14, 15],
     [16, 17, 18, 19],
     [20, 21, 22, 23]]
])

#### 2.1. Заполните элементы от 3 до 19 (включительно) числом -1

Должно получиться:
```
[[ 0,  1,  2, -1],
[-1, -1, -1, -1],
[-1, -1, -1, -1]],

[[-1, -1, -1, -1],
[-1, -1, -1, -1],
[20, 21, 22, 23]]
```

**Обязательно изменить матрицу `A_2_1`, не создать новую**

In [82]:
A_2_1 = A_2_orig.copy()

In [83]:
mask = (A_2_1 >= 3) & (A_2_1 <= 19)
A_2_1[mask] = -1

In [84]:
A_2_1

array([[[ 0,  1,  2, -1],
        [-1, -1, -1, -1],
        [-1, -1, -1, -1]],

       [[-1, -1, -1, -1],
        [-1, -1, -1, -1],
        [20, 21, 22, 23]]])

In [85]:
assert A_2_1.shape == (2, 3, 4), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_2_1, np.array([
    [[ 0,  1,  2, -1],
    [-1, -1, -1, -1],
    [-1, -1, -1, -1]],
    [[-1, -1, -1, -1],
    [-1, -1, -1, -1],
    [20, 21, 22, 23]]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('2.1')

#### 2.2. Заполните элементы от 3 до 19 (включительно) числами 0, 1, 2, ... 

Должно получиться:
```
[[ 0,  1,  2,  0],
[ 1,  2,  3,  4],
[ 5,  6,  7,  8]],

[[ 9, 10, 11, 12],
[13, 14, 15, 16],
[20, 21, 22, 23]]
```

**Обязательно изменить матрицу `A_2_2`, не создать новую**

In [86]:
A_2_2 = A_2_orig.copy()

In [87]:
mask = (A_2_2 >= 3) & (A_2_2 <= 19)
A_2_2[mask] = A_2_2[mask] - 3

In [88]:
A_2_2

array([[[ 0,  1,  2,  0],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [20, 21, 22, 23]]])

In [89]:
assert A_2_2.shape == (2, 3, 4), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_2_2, np.array([
    [[ 0,  1,  2,  0],
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8]],
    [[ 9, 10, 11, 12],
    [13, 14, 15, 16],
    [20, 21, 22, 23]]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('2.2')

#### 2.3. Создайте новую матрицу, у которой все элементы со значениями `A_2` от 3 до 19 (включительно) заполнены числом 1, а все остальные элементы заполнены числом -1

Должно получиться:
```
[[-1, -1, -1,  1],
[ 1,  1,  1,  1],
[ 1,  1,  1,  1]],

[[ 1,  1,  1,  1],
[ 1,  1,  1,  1],
[-1, -1, -1, -1]]
```

**Обязательно создать новую матрицу, не используя мутацию (т.е. в одну команду), исходная матрица не должна измениться**

In [90]:
A_2 = A_2_orig.copy()

In [91]:
A_2_3 = np.where((A_2 >= 3) & (A_2 <= 19), 1, -1)

In [92]:
A_2_3

array([[[-1, -1, -1,  1],
        [ 1,  1,  1,  1],
        [ 1,  1,  1,  1]],

       [[ 1,  1,  1,  1],
        [ 1,  1,  1,  1],
        [-1, -1, -1, -1]]])

In [93]:
assert A_2_3.shape == (2, 3, 4), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_2, A_2_orig), 'Ошибка (`A_2` не должна измениться), переделайте или пропускайте задание'
assert np.allclose(A_2_3, np.array([
    [[-1, -1, -1,  1],
    [ 1,  1,  1,  1],
    [ 1,  1,  1,  1]],
    [[ 1,  1,  1,  1],
    [ 1,  1,  1,  1],
    [-1, -1, -1, -1]]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('2.3')

#### 2.4. ⭐️ Доп. задание. Создайте новую матрицу, у которой все элементы со значениями `A_2` от 3 до 19 (включительно) заполнены числами 0, 1, 2, ..., а все остальные элементы заполнены числами 0, -1, -2, ...

Должно получиться:
```
[[[  0,  -1,  -2,  -3],
[ -4,  -5,  -6,  -7],
[ -8,   0,   1,   2]],

[[  3,   4,   5,   6],
[  7,   8,   9,  10],
[ -9, -10, -11, -12]]]
```

**Обязательно создать новую матрицу, не используя мутацию (т.е. в одну команду), исходная матрица не должна измениться**

In [94]:
A_2 = A_2_orig.copy()

In [95]:
A_2_4 = np.where((A_2 >= 9 & A_2 <= 19))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [96]:
A_2_4

NameError: name 'A_2_4' is not defined

In [97]:
assert A_2_4.shape == (2, 3, 4), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A_2, A_2_orig), 'Ошибка (`A_2` не должна измениться), переделайте или пропускайте задание'
assert np.allclose(A_2_4, np.array([
    [[  0,  -1,  -2,  -3],
    [ -4,  -5,  -6,  -7],
    [ -8,   0,   1,   2]],
    
    [[  3,   4,   5,   6],
    [  7,   8,   9,  10],
    [ -9, -10, -11, -12]]
])), 'Ошибка, переделайте или пропускайте задание'
ok.add('2.4')

NameError: name 'A_2_4' is not defined

### 3. Линейная алгебра

**Задание:** решите простые матричные уравнения.

**Не изменяйте массивы**.


#### Подготовка

In [98]:
# здесь матрица создаётся вручную, чтобы не упрощать выполнение предыдущих заданий,
# на практике никогда не применяйте такой подход для крупных матриц
A = np.array([
    [ 10,  2,  3],
    [ 4,  5,  6],
    [ 7,  8, 9]
])
b = np.array([0, 1, 2])

In [99]:
C = np.array([
    [ 0,  1,  2],
    [ 3,  4,  5],
    [ 6,  7, 8]
])
d = np.array([0, 1, 2])

#### 3.1. Решите уравнение $A x = b$

In [100]:
x_3_1 = (np.linalg.inv(A) @ b)

In [101]:
x_3_1

array([ 2.77555756e-17,  1.00000000e+00, -6.66666667e-01])

In [102]:
assert x_3_1.shape == (3,), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(A @ x_3_1, b), 'Ошибка, переделайте или пропускайте задание'
ok.add('3.1')

#### 3.2. Решите уравнение $C x = d$

In [103]:
np.linalg.det(C)
temp = C.T @ C  
x_3_2 = np.linalg.inv(temp) @ d

In [104]:
x_3_2

array([-0.5859375,  0.       ,  0.421875 ])

In [105]:
assert x_3_2.shape == (3,), 'Ошибка, переделайте или пропускайте задание'
assert np.allclose(C @ x_3_2, d), 'Ошибка, переделайте или пропускайте задание'
ok.add('3.2')

AssertionError: Ошибка, переделайте или пропускайте задание

#### 3.3. Почему так получилось, что решение 3.1 может не подойти для 3.2?

Потому что для A матрицы существует обратная ей и можно найти как x = A^-1 x b, а для C обратной нет она выражденная

Можно решить инверсией x = (C^T x C)^-1 @ d, но не получилось

## Итоги

In [106]:
print(f'Выполнены задания: {ok}')
print(f'Осталось: {all_tasks - ok}')

Выполнены задания: {'3.1', '2.2', '2.3', '1.2', '1.1', '2.1'}
Осталось: {'3.2', '2.4'}
